metadata:
  name: mautic-build-workflow
  namespace: de0974-tools
spec:
  templates:
    - name: main
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: clone
            template: clone
            arguments: {}
        - - name: build-deploy-mautic
            template: build-deploy-mautic
            arguments: {}

    - name: clone
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/alpine/git:v2.26.2'
        args:
          - clone
          - '--depth'
          - '1'
          - '--branch'
          - '{{workflow.parameters.GIT_REF}}'
          - '--single-branch'
          - '{{workflow.parameters.GIT_REPO}}'
        workingDir: /mnt/vol
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

    - name: build-deploy-mautic
      arguments: {}
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'docker.io/openshift/origin-cli:latest'
        command:
          - sh
          - '-c'
        args: 
          - >-
            oc project -n {{workflow.parameters.NAMESPACE}};

            oc process -f ./openshift/secret.yaml 
            -p APP_NAME={{workflow.parameters.APP_NAME}}
            -p DATABASE_NAME={{workflow.parameters.DATABASE_NAME}}
            -p DATABASE_USER={{workflow.parameters.DATABASE_USER}}
            -p DATABASE_USER_PASSWORD={{workflow.parameters.DATABASE_USER_PASSWORD}}
            -p DATABASE_ROOT_PASSWORD={{workflow.parameters.DATABASE_ROOT_PASSWORD}}
            | oc apply -f - -n {{workflow.parameters.NAMESPACE}};

            oc process -f ./openshift/mautic.yaml 
            -p APP_NAME={{workflow.parameters.APP_NAME}}
            -p GIT_REF={{workflow.parameters.GIT_REF}} 
            -p GIT_REPO={{workflow.parameters.GIT_REPO}} 
            -p NAMESPACE={{workflow.parameters.NAMESPACE}} 
            -p STORAGE_CLASS_NAME={{workflow.parameters.STORAGE_CLASS_NAME}} 
            -p IMAGE_TAG={{workflow.parameters.IMAGE_TAG}}
            | oc apply -f - -n {{workflow.parameters.NAMESPACE}}

        workingDir: /mnt/vol/mautic-openshift
        resources:
          limits:
            cpu: 100m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        volumeMounts:
          - name: work
            mountPath: /mnt/vol

  entrypoint: main
  arguments: {}
  serviceAccountName: workflow-creator
  volumeClaimTemplates:
    - metadata:
        name: work
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 128Mi
        storageClassName: netapp-file-standard
      status: {}
  imagePullSecrets:
    - name: dockerhub-secret-mautic
