kind: Template
apiVersion: v1
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: ${APP_NAME}-init
        name: 'mautic'
      name: ubuntu
    spec:
      lookupPolicy:
        local: false
      tags:
      - annotations:
          openshift.io/imported-from: ubuntu:latest
        from:
          kind: DockerImage
          name: ubuntu:latest
        generation: null
        importPolicy: {}
        name: latest
        referencePolicy:
          type: ""
    status:
      dockerImageRepository: ""
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: ${APP_NAME}-init
        name: 'mautic'
      name: ${APP_NAME}-init
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ""
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: ${APP_NAME}-init
        name: 'mautic'
      name: ${APP_NAME}-init
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}-init:latest
      postCommit: {}
      resources: {}
      source:
        contextDir: mautic-init
        git:
          ref: email-themes
          uri: https://github.com/bcgov/mautic-openshift
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: ubuntu:latest
        type: Docker
      triggers:
      - type: ConfigChange
      - imageChange: {}
        type: ImageChange
    status:
      lastVersion: 0

parameters:
- name: APP_NAME
  displayName: App name
  description: the value used to group components by a common name
  required: true
- name: GIT_REF
  displayName: Git Branch
  description: the git branch to build from
  required: true
- name: GIT_REPO
  displayName: Git repository
  description: the git repo to build from
  required: true