apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: mautic-init
    name: ubuntu
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ubuntu:latest
      from:
        kind: DockerImage
        name: ubuntu:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: mautic-init
    name: mautic-init
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: mautic-init
    name: mautic-init
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: mautic-init:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: mautic-init
      git:
        ref: email-themes
        uri: https://github.com/bcgov/mautic-openshift
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:latest
      type: Docker
    triggers:
    - github:
        secret: YqsGcTl8eAQZemodIrOz
      type: GitHub
    - generic:
        secret: Feu1vIWmFdUHRIdDA6PN
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
