kind: Template
apiVersion: v1
parameters:
  - name: NAMESPACE
objects:
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    spec:
      description: 'allow ${NAMESPACE} namespace to talk to the internet.'
      source:
        - - '$namespace=${NAMESPACE}'
      destination:
        - - 'ext:network=any'
    metadata:
      name: egress-internet
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    spec:
      description: 'allow ${NAMESPACE} namespace to talk to itself'
      source:
        - - '$namespace=${NAMESPACE}'
      destination:
        - - '$namespace=${NAMESPACE}'
    metadata:
      name: intra-namespace-comms
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    spec:
      description: 'allow ${NAMESPACE} pods to talk to the k8s api'
      destination:
        - - 'int:network=internal-cluster-api-endpoint'
      source:
        - - '$namespace=${NAMESPACE}'
    metadata:
      name: int-cluster-k8s-api-comms
