kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Secret
    stringData:
      database-name: ${APP_NAME}_db
      database-password: ${DATABASE_USER_PASSWORD}
      database-root-password: ${DATABASE_ROOT_PASSWORD}
      database-user: ${DATABASE_USER}
    type: Opaque
    metadata:
      annotations:
        template.openshift.io/expose-database-name: '{.data[''database-name'']}'
        template.openshift.io/expose-password: '{.data[''database-password'']}'
        template.openshift.io/expose-root-password: '{.data[''database-root-password'']}'
        template.openshift.io/expose-username: '{.data[''database-user'']}'
      labels:
        component: secret
        deploymentConfig: ${APP_NAME}
        app: ${APP_NAME}
      name: ${APP_NAME}-db
parameters:
- name: APP_NAME
  displayName: App name
  description: the value used to group components by a common name
- name: DATABASE_USER
  description: the database root user
  displayName: Database Root Username
  from: '[a-zA-Z0-9]{8}'
  generate: expression
- name: DATABASE_USER_PASSWORD
  description: The database user password
  displayName: Database User Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression
- name: DATABASE_ROOT_PASSWORD
  description: The database root password
  displayName: Database Root User Password
  from: '[a-zA-Z0-9]{8}'
  generate: expression